apiVersion: apps/v1
kind: Deployment
metadata: { name: alpha }
spec:
  replicas: 1
  selector: { matchLabels: { app: alpha } }
  template:
    metadata: { labels: { app: alpha } }
    spec:
      containers:
      - name: alpha
        image: musarafay/alpha:1.0
        ports: [{ containerPort: 5000 }]
---
apiVersion: v1
kind: Service
metadata: { name: alpha }
spec:
  selector: { app: alpha }
  ports: [{ port: 80, targetPort: 5000 }]
