apiVersion: apps/v1
kind: Deployment
metadata: { name: bravo }
spec:
  replicas: 1
  selector: { matchLabels: { app: bravo } }
  template:
    metadata: { labels: { app: bravo } }
    spec:
      containers:
      - name: bravo
        image: musarafay/bravo:1.0
        ports: [{ containerPort: 5000 }]
---
apiVersion: v1
kind: Service
metadata: { name: bravo }
spec:
  selector: { app: bravo }
  ports: [{ port: 80, targetPort: 5000 }]
